### ISSUE TITLE
Error when showing help

### ISSUE THREAD

**Issue by gabrielgradinaru** [vitaliemaldur/tbl#21]
gaby@gaby-VirtualBox:~/PycharmProjects/tbl$ python3 tbl/manage.py --help
usage: manage.py [-h] [-t {True,False}] [-p {facebook,twitter}] [-d]

Fetch links, store and share them

optional arguments:
  -h, --help            show this help message and exit
  -t {True,False}, --test {True,False}
                        test available scrapers
  -p {facebook,twitter}, --post {facebook,twitter}
                        post on social media
  -d, --debug           enable debugging statements
Exception ignored in: <bound method BaseInterface.__del__ of <tbl.interfaces.twitter.TwitterInterface object at 0x7f00dc923d68>>
Traceback (most recent call last):
  File "/home/gaby/PycharmProjects/tbl/tbl/interfaces/base.py", line 35, in **del**
  File "/home/gaby/.local/lib/python3.5/site-packages/aiohttp/client.py", line 430, in close
  File "/home/gaby/.local/lib/python3.5/site-packages/aiohttp/connector.py", line 233, in close
AttributeError: 'NoneType' object has no attribute 'create_future'
Exception ignored in: <bound method ClientSession.__del__ of <aiohttp.client.ClientSession object at 0x7f00d9645588>>
Traceback (most recent call last):
  File "/home/gaby/.local/lib/python3.5/site-packages/aiohttp/client.py", line 84, in **del**
  File "/home/gaby/.local/lib/python3.5/site-packages/aiohttp/client.py", line 430, in close
  File "/home/gaby/.local/lib/python3.5/site-packages/aiohttp/connector.py", line 233, in close
AttributeError: 'NoneType' object has no attribute 'create_future'
Exception ignored in: <bound method BaseInterface.__del__ of <tbl.interfaces.facebook.FacebookInterface object at 0x7f00d7bdfe48>>
Traceback (most recent call last):
  File "/home/gaby/PycharmProjects/tbl/tbl/interfaces/base.py", line 35, in **del**
  File "/home/gaby/.local/lib/python3.5/site-packages/aiohttp/client.py", line 430, in close
  File "/home/gaby/.local/lib/python3.5/site-packages/aiohttp/connector.py", line 233, in close
AttributeError: 'NoneType' object has no attribute 'create_future'
Exception ignored in: <bound method ClientSession.__del__ of <aiohttp.client.ClientSession object at 0x7f00d7bdfe80>>
Traceback (most recent call last):
  File "/home/gaby/.local/lib/python3.5/site-packages/aiohttp/client.py", line 84, in **del**
  File "/home/gaby/.local/lib/python3.5/site-packages/aiohttp/client.py", line 430, in close
  File "/home/gaby/.local/lib/python3.5/site-packages/aiohttp/connector.py", line 233, in close
AttributeError: 'NoneType' object has no attribute 'create_future'

**Comment by gabrielgradinaru** [comment]
The quick and dirty solution is to move the instantiation of 'TwitterInterface' class into post 'corotine' where it is used. 
The better solution is to find the cause of the error and fix that. Will continue to look into this.

**Comment by gabrielgradinaru** [comment]
``` python
import aiohttp
class SimpleClass:
    def __init__(self):
        self.session = aiohttp.ClientSession()
    def __del__(self):
        self.session.close()
obj = SimpleClass()
# or sys.exit()
raise SystemExit
```

It is strange that when raising SystemExit we get an error, but when script terminated normally we don't get the error.

**Comment by gabrielgradinaru** [comment]
Got answer from aiohttp mainterner:
"aiohttp depends on asyncio loop.
You shouldn't rely on **del** but make graceful shutdown and close the loop after.
Also ClientSession.close() is a coroutine, it means the session.close() call is not allowed from regular functions but should be used as await session.close()"
